# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-27 18:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RememberToken',
            fields=[
                ('token_hash', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, null=True)),
                ('created_initial', models.DateTimeField(editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remember_me_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'remembertoken',
            },
        ),
    ]
