# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-27 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_remember', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remembertoken',
            name='token_hash',
            field=models.CharField(max_length=165, primary_key=True, serialize=False),
        ),
    ]
